// Generates supabase/migrations/20261007000300_seed_menu.sql from scripts/menu-data.mjs.
// Usage: npm run seed:generate
import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { categories, menu } from './menu-data.mjs'

const here = path.dirname(fileURLToPath(import.meta.url))
const OUT = path.join(here, '..', 'supabase', 'migrations', '20261007000300_seed_menu.sql')

/** Deterministic UUID so re-running the seed never duplicates rows. */
export function uid(key) {
  const h = createHash('sha1').update(`mgl-food-hub:${key}`).digest('hex')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-5${h.slice(13, 16)}-${((parseInt(h[16], 16) & 0x3) | 0x8).toString(16)}${h.slice(17, 20)}-${h.slice(20, 32)}`
}

function parseVariants(spec, where) {
  const parts = spec.split(' | ').map((p) => p.trim())
  return parts.map((part) => {
    if (/^\d+(\.\d+)?$/.test(part)) return { label: 'Regular', price: Number(part), addon: null }
    const m = part.match(/^(.*?)\s+(\d+(?:\.\d+)?)(?:\s+\+(\d+(?:\.\d+)?))?$/)
    if (!m) throw new Error(`Bad variant "${part}" in ${where}`)
    return { label: m[1], price: Number(m[2]), addon: m[3] ? Number(m[3]) : null }
  })
}

export function parseMenu() {
  const stores = []
  let store = null
  let section = null
  for (const raw of menu.split('\n')) {
    const line = raw.trim()
    if (!line) continue
    if (line.startsWith('STORE ')) {
      const [slug, name, category, hours] = line.slice(6).split(' | ').map((s) => s.trim())
      const [open, close] = hours.split('-')
      if (!categories.some((c) => c.slug === category)) throw new Error(`Unknown category ${category}`)
      store = { slug, name, category, open, close, tagline: null, address: null, note: null, sections: [] }
      stores.push(store)
      section = null
    } else if (/^(tagline|address|note):/.test(line)) {
      const idx = line.indexOf(':')
      store[line.slice(0, idx)] = line.slice(idx + 1).trim()
    } else if (line.startsWith('## ')) {
      const [name, note] = line.slice(3).split(' :: ')
      section = { name: name.trim(), note: note?.trim() ?? null, products: [] }
      store.sections.push(section)
    } else {
      if (!section) throw new Error(`Product outside section: ${line}`)
      const [head, ...mods] = line.split(' ; ')
      const eq = head.indexOf(' = ')
      if (eq < 0) throw new Error(`Bad product line: ${line}`)
      const product = {
        name: head.slice(0, eq).trim(),
        variants: parseVariants(head.slice(eq + 3).trim(), `${store.slug}/${line}`),
        badge: null,
        description: null,
        groups: [],
      }
      for (const mod of mods) {
        const m = mod.trim()
        if (m.startsWith('#')) product.badge = m.slice(1)
        else if (m.startsWith('~')) product.description = m.slice(1).trim()
        else if (m.startsWith('@')) {
          const idx = m.indexOf(':')
          product.groups.push({
            name: m.slice(1, idx).trim(),
            choices: m.slice(idx + 1).split(' / ').map((c) => c.trim()),
          })
        } else throw new Error(`Unknown modifier "${m}" in ${line}`)
      }
      section.products.push(product)
    }
  }
  return stores
}

const q = (v) => (v === null || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`)
const money = (n) => (n === null ? 'null' : n.toFixed(2))

export function buildSeed(stores) {
  const out = []
  out.push('-- =====================================================================')
  out.push('-- MGL Food Hub — menu seed. GENERATED by scripts/generate-seed.mjs.')
  out.push('-- Do not edit by hand; edit scripts/menu-data.mjs and regenerate.')
  out.push('-- =====================================================================')
  out.push('')
  out.push('insert into public.hub_categories (id, name, slug, sort) values')
  out.push(
    categories
      .map((c, i) => `  (${q(uid(`cat:${c.slug}`))}, ${q(c.name)}, ${q(c.slug)}, ${i + 1})`)
      .join(',\n') + '\non conflict (id) do nothing;',
  )
  out.push('')

  const rows = { stores: [], sections: [], products: [], variants: [], groups: [], choices: [] }
  stores.forEach((s, si) => {
    const storeId = uid(`store:${s.slug}`)
    const img = `/menus/${s.slug}.jpg`
    rows.stores.push(
      `  (${q(storeId)}, ${q(s.slug)}, ${q(s.name)}, ${q(s.tagline)}, ${q(uid(`cat:${s.category}`))}, ${q(s.open)}, ${q(s.close)}, ${q(s.address)}, ${q(s.note)}, ${q(img)}, ${q(img)}, true, ${si + 1})`,
    )
    s.sections.forEach((sec, ci) => {
      const secKey = `${s.slug}:${ci}`
      const secId = uid(`section:${secKey}`)
      rows.sections.push(`  (${q(secId)}, ${q(storeId)}, ${q(sec.name)}, ${q(sec.note)}, ${ci + 1})`)
      sec.products.forEach((p, pi) => {
        const pKey = `${secKey}:${pi}`
        const pId = uid(`product:${pKey}`)
        rows.products.push(
          `  (${q(pId)}, ${q(storeId)}, ${q(secId)}, ${q(p.name)}, ${q(p.description)}, ${q(p.badge)}, ${pi + 1})`,
        )
        p.variants.forEach((v, vi) => {
          rows.variants.push(
            `  (${q(uid(`variant:${pKey}:${vi}`))}, ${q(pId)}, ${q(v.label)}, ${money(v.price)}, ${money(v.addon)}, ${vi + 1})`,
          )
        })
        p.groups.forEach((g, gi) => {
          const gId = uid(`group:${pKey}:${gi}`)
          rows.groups.push(`  (${q(gId)}, ${q(pId)}, ${q(g.name)}, true)`)
          g.choices.forEach((c, chi) => {
            rows.choices.push(`  (${q(uid(`choice:${pKey}:${gi}:${chi}`))}, ${q(gId)}, ${q(c)}, 0.00, ${chi + 1})`)
          })
        })
      })
    })
  })

  const block = (table, cols, list) => {
    out.push(`insert into public.${table} (${cols}) values`)
    out.push(list.join(',\n') + '\non conflict (id) do nothing;')
    out.push('')
  }
  block(
    'stores',
    'id, slug, name, tagline, hub_category_id, open_time, close_time, address, contact_note, cover_image_url, menu_image_url, is_accepting_orders, sort',
    rows.stores,
  )
  block('menu_sections', 'id, store_id, name, note, sort', rows.sections)
  block('products', 'id, store_id, section_id, name, description, badge, sort', rows.products)
  block('product_variants', 'id, product_id, label, price, addon_price, sort', rows.variants)
  block('option_groups', 'id, product_id, name, is_required', rows.groups)
  block('option_choices', 'id, group_id, label, price_delta, sort', rows.choices)

  out.push('-- Balsa Chicken "Buttered Half" is not seeded: its price must be confirmed')
  out.push('-- from the menu photo first (see scripts/menu-data.mjs).')
  return { sql: out.join('\n') + '\n', counts: Object.fromEntries(Object.entries(rows).map(([k, v]) => [k, v.length])) }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const stores = parseMenu()

  // Peachy-Peachy totals must equal the TOTAL column on the menu exactly.
  const expectedPeachy = [168, 198, 258, 330, 408, 480, 648, 792]
  const peachy = stores.find((s) => s.slug === 'anny-dading-peachy-peachy').sections[0].products[0]
  peachy.variants.forEach((v, i) => {
    if (Math.round((v.price + v.addon) * 100) !== expectedPeachy[i] * 100)
      throw new Error(`Peachy total mismatch for ${v.label}`)
  })

  const { sql, counts } = buildSeed(stores)
  writeFileSync(OUT, sql)
  console.log(`Wrote ${path.relative(process.cwd(), OUT)}`)
  console.log(`stores=${counts.stores} sections=${counts.sections} products=${counts.products} variants=${counts.variants} option_groups=${counts.groups} option_choices=${counts.choices}`)
}
